version: "3"
services:
  node:
    image: "${NODE_IMAGE_NAME}:${NODE_IMAGE_TAG}"
    container_name: node-app
    restart: always
    ports:
      - "${NODE_PORT}:4000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - nodejs_app

  mongodb:
    image: mongo
    # command: --port ${MONGO_PORT}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - nodejs_app

  mongo-express:
    image: mongo-express
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    volumes:
      - ./_data/ME:/data/db
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_BASICAUTH="true"
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_UI_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_UI_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - nodejs_app

  flutter:
    image: "${FLUTTER_IMAGE_NAME}:${FLUTTER_IMAGE_TAG}"
    container_name: flutter-app
    restart: always
    ports:
      - "${FLUTTER_PC_PORT}:80"
    depends_on:
      - node
    networks:
      - nodejs_app

volumes:
  mongo_data:

networks:
  nodejs_app:
